add git-st plus tidy up

diff --git a/src/gagu/usr/share/gagu/utils b/src/gagu/usr/share/gagu/utils
--- a/src/gagu/usr/share/gagu/utils
+++ b/src/gagu/usr/share/gagu/utils
@@ -1,17 +1,21 @@
 #some utils used by gagu
 
 check-git() {
-        git status > /dev/null || exit 1
+	git status > /dev/null || exit 1
 }
 
 require-package() {
-	if [ $# -ne 1 ]; then
+	if [[ $# -ne 1 ]]; then
 		echo no package specified
 		exit 1
 	fi
 	local package="$1"
 	if ! dpkg-query -W --showformat='${Status}\n' "$package" 2>/dev/null | grep -q 'install ok install'; then
-        	echo "error: $package required but not installed"
-	        exit 1
+		echo "error: $package required but not installed"
+		exit 1
 	fi
 }
+
+if [[ ! $skip_git_check ]]; then
+	check-git
+fi
